config.code=232424
config.username=iker
config.message=Hola que tal :3
config.cat = ":3"
config.listOfValues=hola,que,tal,hoy

# Objeto JSON
config.valuesMap={product: 'Teclado', description: 'Teclado mecanico red switches', price: '50'}